# Generated by Django 5.2 on 2025-04-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='State',
            new_name='state',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default='pending', max_length=15),
            preserve_default=False,
        ),
    ]
